### ISSUE TITLE
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at ..\aten\src\THC\THCGeneral.cpp:51

### ISSUE THREAD

**Issue by MiaoQiaowei** [xinntao/BasicSR#182]
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at ..\aten\src\THC\THCGeneral.cpp:51

How can I slove this problem?
Please help me.
Thanks in advance!

**Comment by xinntao** [comment]
run in python
```
import torch
print(torch.cuda.is_available())
```
See if it is OK.

**Comment by MiaoQiaowei** [comment]
The return value is True..

**Comment by MiaoQiaowei** [comment]
I have tried many times..
Traceback (most recent call last):
  File "/home/root123/MQW/BasicSR/codes/train.py", line 232, in <module>
    main()
  File "/home/root123/MQW/BasicSR/codes/train.py", line 133, in main
    model = create_model(opt)
  File "/home/root123/MQW/BasicSR/codes/models/__init__.py", line 16, in create_model
    m = M(opt)
  File "/home/root123/MQW/BasicSR/codes/models/SRGAN_model.py", line 24, in __init__
    self.netG = networks.define_G(opt).to(self.device)
  File "/home/root123/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/root123/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/root123/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/home/root123/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/home/root123/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/cuda/__init__.py", line 163, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1556653183467/work/aten/src/THC/THCGeneral.cpp:51

**Comment by xinntao** [comment]
Did you set the wrong CUDA_VISIBLE_DEVICES?

**Comment by MiaoQiaowei** [comment]
I have two RTX2080
without settings, I have this problem, so I have tried:
os.environ ['CUDA_VISIBLE_DEVICES'] ="0"
os.environ ['CUDA_VISIBLE_DEVICES'] ="0,1"

And get the same error

**Comment by xinntao** [comment]
Have you solved this problem? 
In the config file, you also need to reset the `gpu_ids`.

**Comment by MiaoQiaowei** [comment]
Thx，I have solved this problem.

**Comment by xinntao** [comment]
What is the cause of this problem?

**Comment by MiaoQiaowei** [comment]
Just need to update cuda and try to install pytorch again.
cuda 10.1 and cuDNN 10.1 with pytorch 1.1.0

**Comment by xinntao** [comment]
OK, thanks~
