### ISSUE TITLE
Cuda out of memory but worked on other tests

### ISSUE THREAD

**Issue by torrentguy** [xinntao/BasicSR#194]
i first trained an experiment with n_workers set to 47 and batch_size set to 20.

now im training a new model that cant even run n_workers: 1 and batch_size:1.
here's my output:
`CUDA out of memory. Tried to allocate 1.48 GiB (GPU 0; 8.00 GiB total capacity; 2.60 GiB already allocated; 282.65 MiB free; 3.32 GiB cached)`

why is this happening? i updated my drivers and still the same results

**Comment by xinntao** [comment]
47 is too large. It will start `n_workers` for each GPU.

It seems your GPU memory is not enough for training the model. Try to decrease the batch size.

**Comment by torrentguy** [comment]
I already said that even n_workers: 1and batch_size:1 was too much, seems the problem was that i wasnt using tiles and full res frames
